# Generated by Django 4.2.4 on 2023-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Koder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("generation", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=25)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("finished", "Finished"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("s", "Small"), ("m", "Medium"), ("l", "Large")],
                        default="s",
                        max_length=1,
                    ),
                ),
                ("birthdate", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
