# Generated by Django 4.2.4 on 2023-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamp", "0002_alter_bootcamp_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="koder",
            name="first_name",
            field=models.CharField(max_length=254),
        ),
    ]
